backend:
  name: github
  repo: Zum0DePapaya/portfolio-cms
  branch: master

media_folder: "src/assets/images"
public_folder: "/assets/images"

collections:
  - name: "settings"
    label: "Settings"
    files:
      - label: "Landing Page"
        name: "landing"
        file: "src/_data/landing.json"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Bio", name: "bio", widget: "text"}
          - {label: "Profile Image", name: "profile_image", widget: "image"}
          - {label: "LinkedIn URL", name: "linkedin_url", widget: "string"}
          - {label: "GitHub URL", name: "github_url", widget: "string"}

  - name: "projects"
    label: "Projects"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight (Order)", name: "weight", widget: "number", value_type: "int", default: 10}
      - {label: "Category", name: "category", widget: "select", options: ["games", "tools"]}
      - {label: "Thumbnail Image", name: "thumbnail", widget: "image"}
      - {label: "Hover Description (HTML allowed)", name: "hover_description", widget: "text"}
      - {label: "Full Width Card", name: "full_width", widget: "boolean", default: false, required: false}
      - {label: "Project Body", name: "body", widget: "markdown"}
